### ISSUE TITLE
Element-Web "circles" forever, Synapse error "Failed to introspect token"

### ISSUE THREAD

**Issue by jacotec** [matrix-org/matrix-authentication-service#1864]
I've managed to install MAS now on my test server, User registration works, email verification also.

Then a window appears to grant permissions to Element-Web in the login process ... but after confirming I expect Element-Web to log in, instead it's "forever circling".

In the Synapse log I see:

```
2023-09-28 11:06:06,622 - synapse.api.auth.msc3861_delegated - 259 - ERROR - GET-698371 - Failed to introspect token
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/api/auth/msc3861_delegated.py", line 257, in get_user_by_access_token
    introspection_result = await self._introspect_token(token)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/api/auth/msc3861_delegated.py", line 178, in _introspect_token
    response = await self._http_client.request(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/client.py", line 369, in request
    logger.debug("Sending request %s %s", method, redact_uri(uri))
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/__init__.py", line 38, in redact_uri
    uri = ACCESS_TOKEN_RE.sub(r"\1<redacted>\3", uri)
TypeError: expected string or bytes-like object
2023-09-28 11:06:06,623 - synapse.http.server - 124 - INFO - GET-698371 - <XForwardedForRequest at 0x7f58c69d47f0 method='GET' uri='/_matrix/client/r0/sync?timeout=30000&since=s429471_57579471_0_692213_121803_42_20186_6828218_0_3&set_presence=offline&filter=%7B%22room%22%3A%7B%22timeline%22%3A%7B%22limit%22%3A50%7D%7D%7D' clientproto='HTTP/1.0' site='8448'> SynapseError: 503 - Unable to introspect the access token
```

**Comment by jacotec** [comment]
Created another new user with a completely new email address (the previous email address was "known" to Synapse before from a login user), now I'm getting to the same point, but:

![image](https://github.com/matrix-org/matrix-authentication-service/assets/3321655/f7cb1b04-53be-4d0e-9b86-a7e745451778)


MAS log:

`2023-09-28T09:28:30.285098Z ERROR http.server.request{otel.kind="server" otel.name="POST /complete-compat-sso/:grant_id" network.protocol.name="http" network.protocol.version="1.1" http.method="POST" url.path="/complete-compat-sso/01HBDHTE3YT972CCBRAECPMHC7" url.scheme="http" http.route="/complete-compat-sso/:grant_id" user_agent.original="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"}:handlers.compat.login_sso_complete.post{compat_sso_login.id=01HBDHTE3YT972CCBRAECPMHC7}: mas_handlers::compat::login_sso_complete: error=Internal error: Invalid database operation (RepositoryError { source: InvalidOperation { source: Some(InvalidTransitionError) } })`

**Comment by sandhose** [comment]
This feels like there is a problem between MAS and Synapse, especially to do the introspection request.
When Synapse introspects an incoming token, it will:

 1. Load the OP metadata by doing a GET request to `<issuer>/.well-known/openid-configuration`, where `<issuer>` is `experimental_features.msc3861.issuer` in Synapse configuration. The result is then cached.
 2. From the metadata, get the `introspection_endpoint`. From MAS' POV, this one is constructed like `<public_base>/oauth2/introspect`, where `<public_base>` is `http.public_base` in MAS' configuration.
 3. Post the access token to the `introspection_endpoint`

With the error you got, it feels like (1) went fine, but on (2)/(3), the `introspection_endpoint` was null/not present.

Can you make sure that:

 - Synapse can GET `<issuer>/.well-known/openid-configuration`
 - Synapse can POST on whatever `introspection_endpoint` is present in that document

The second error you're pointing out is because that page got reloaded twice and the feedback for this is not the best. I opened an issue specifically for this here: https://github.com/matrix-org/matrix-authentication-service/issues/1865

**Comment by jacotec** [comment]
Seems to be https://github.com/matrix-org/matrix-authentication-service/pull/1775

Is this already in 0.2.0?

**Comment by sandhose** [comment]
> Seems to be #1775
> 
> Is this already in 0.2.0?

Actually, that might be related. Can you try and run the latest version, either from the Docker image with the tag `sha-a62aa87`, or out of the binaries available here: https://github.com/matrix-org/matrix-authentication-service/actions/runs/6312929380

**Comment by jacotec** [comment]
> * Load the OP metadata by doing a GET request to `<issuer>/.well-known/openid-configuration`, where `<issuer>` is `experimental_features.msc3861.issuer` in Synapse configuration. The result is then cached.
> * From the metadata, get the `introspection_endpoint`. From MAS' POV, this one is constructed like `<public_base>/oauth2/introspect`, where `<public_base>` is `http.public_base` in MAS' configuration.

There is no "introspection_endpoint" in the well-known, where does it get this from?

![image](https://github.com/matrix-org/matrix-authentication-service/assets/3321655/df31f098-9303-4539-a0b0-9676c6353bd7)

> Can you make sure that:
> 
> * Synapse can GET `<issuer>/.well-known/openid-configuration`
> * Synapse can POST on whatever `introspection_endpoint` is present in that document

I have added an "introspection_endpoint" to the well-known just in case this is a documentation issue, but this does not change something.
I can curl the well-known on the Synapse server:

```
root@flairy:~# curl https://flairy.de/.well-known/openid-configuration
{"issuer":"https://flairy.de/","authorization_endpoint":"https://auth.flairy.de/authorize","token_endpoint":"https://auth.flairy.de/oauth2/token","jwks_uri":"https://auth.flairy.de/oauth2/keys.json","registration_endpoint":"https://auth.flairy/oauth2/registration","introspection_endpoint":"https://auth.flairy/oauth2/introspect","//":"..."}
```
I have no idea how to test a "POST" to the introspection endpoint

> It's not, so that might actually be related. Can you try and run the latest version, either from the Docker image with the tag `sha-a62aa87`, or out of the binaries available here: https://github.com/matrix-org/matrix-authentication-service/actions/runs/6312929380

I have replaced the mas-cli binary with the one from your link (from /target/x86_64-unknown-linux-musl), but no change.

This simply does not work ...

**Comment by jacotec** [comment]
... Key Backup issue? How is this related to MAS?

`MatrixError: [501] Resetting cross signing keys is not yet supported with MSC3861 (https://flairy.de/_matrix/client/unstable/keys/device_signing/upload)`
